/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal.View;

import java.awt.event.ActionListener;

/**
 *
 * @author josh
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    private int mouseX;
    private int mouseY;

    public MainGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void listen(ActionListener controller) {
        this.btnCareers.addActionListener(controller);
        this.btnCourses.addActionListener(controller);
        this.btnStudyProgram.addActionListener(controller);
        this.btnUsers.addActionListener(controller);
        this.btnMenu.addActionListener(controller);
        this.btnPlanCourses.addActionListener(controller);
        this.btnExit.addActionListener(controller);
        this.btnUsersCareer.addActionListener(controller);
    }

    public PanelUsers getPanelUsers() {
        return panelUsers1;
    }

    public PanelStudyProgram getPanelStudyProgram() {
        return panelStudyProgram1;
    }

    public PanelCareer getPanelCareer() {
        return panelCareer1;
    }

    public PanelCourse getPanelCourse() {
        return panelCourse1;
    }

    public PanelMain getPanelMain() {
        return panelMain1;
    }

    public PanelUsersAdminUsers getPanelUsersAdminUsers() {
        return panelUsersAdminUsers1;
    }

    public PanelPlanCourse getPanelPlanCourse() {
        return panelPlanCourse1;
    }

    public PanelUsersCareer getPanelUsersCareer() {
        return panelUsersCareer1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCourses = new javax.swing.JButton();
        btnCareers = new javax.swing.JButton();
        btnStudyProgram = new javax.swing.JButton();
        btnUsers = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnPlanCourses = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnUsersCareer = new javax.swing.JButton();
        tbPanel = new javax.swing.JTabbedPane();
        panelUsers1 = new com.mycompany.proyectofinal.View.PanelUsers();
        panelStudyProgram1 = new com.mycompany.proyectofinal.View.PanelStudyProgram();
        panelCareer1 = new com.mycompany.proyectofinal.View.PanelCareer();
        panelCourse1 = new com.mycompany.proyectofinal.View.PanelCourse();
        panelMain1 = new com.mycompany.proyectofinal.View.PanelMain();
        panelUsersAdminUsers1 = new com.mycompany.proyectofinal.View.PanelUsersAdminUsers();
        panelPlanCourse1 = new com.mycompany.proyectofinal.View.PanelPlanCourse();
        panelUsersCareer1 = new com.mycompany.proyectofinal.View.PanelUsersCareer();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(109, 169, 210));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        btnCourses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCourses.setText("Courses");
        btnCourses.setContentAreaFilled(false);
        btnCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoursesActionPerformed(evt);
            }
        });

        btnCareers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCareers.setText("Careers");
        btnCareers.setContentAreaFilled(false);

        btnStudyProgram.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStudyProgram.setText("Study Program");
        btnStudyProgram.setContentAreaFilled(false);

        btnUsers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUsers.setText("Users");
        btnUsers.setContentAreaFilled(false);

        btnMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenu.setText("Gestión de Actividades Académicas");
        btnMenu.setActionCommand("Menu");
        btnMenu.setContentAreaFilled(false);

        btnPlanCourses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPlanCourses.setText("Plan-Courses");
        btnPlanCourses.setContentAreaFilled(false);

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.setContentAreaFilled(false);

        btnUsersCareer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUsersCareer.setText("Users-Career");
        btnUsersCareer.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(btnUsers)
                .addGap(38, 38, 38)
                .addComponent(btnUsersCareer)
                .addGap(41, 41, 41)
                .addComponent(btnStudyProgram)
                .addGap(34, 34, 34)
                .addComponent(btnCareers)
                .addGap(41, 41, 41)
                .addComponent(btnCourses)
                .addGap(58, 58, 58)
                .addComponent(btnPlanCourses)
                .addGap(45, 45, 45)
                .addComponent(btnExit)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourses)
                    .addComponent(btnCareers)
                    .addComponent(btnStudyProgram)
                    .addComponent(btnUsers)
                    .addComponent(btnMenu)
                    .addComponent(btnPlanCourses)
                    .addComponent(btnExit)
                    .addComponent(btnUsersCareer))
                .addGap(6, 6, 6))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        tbPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        tbPanel.addTab("tab1", panelUsers1);
        tbPanel.addTab("tab2", panelStudyProgram1);
        tbPanel.addTab("tab3", panelCareer1);
        tbPanel.addTab("tab4", panelCourse1);
        tbPanel.addTab("tab5", panelMain1);
        tbPanel.addTab("tab6", panelUsersAdminUsers1);
        tbPanel.addTab("tab7", panelPlanCourse1);
        tbPanel.addTab("tab8", panelUsersCareer1);

        tbPanel.setSelectedIndex(4);

        getContentPane().add(tbPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        this.setLocation(evt.getXOnScreen() - mouseX, evt.getYOnScreen() - mouseY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void btnCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoursesActionPerformed

    }//GEN-LAST:event_btnCoursesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCareers;
    public javax.swing.JButton btnCourses;
    private javax.swing.JButton btnExit;
    public javax.swing.JButton btnMenu;
    public javax.swing.JButton btnPlanCourses;
    public javax.swing.JButton btnStudyProgram;
    public javax.swing.JButton btnUsers;
    public javax.swing.JButton btnUsersCareer;
    private javax.swing.JPanel jPanel1;
    private com.mycompany.proyectofinal.View.PanelCareer panelCareer1;
    private com.mycompany.proyectofinal.View.PanelCourse panelCourse1;
    private com.mycompany.proyectofinal.View.PanelMain panelMain1;
    private com.mycompany.proyectofinal.View.PanelPlanCourse panelPlanCourse1;
    private com.mycompany.proyectofinal.View.PanelStudyProgram panelStudyProgram1;
    private com.mycompany.proyectofinal.View.PanelUsers panelUsers1;
    private com.mycompany.proyectofinal.View.PanelUsersAdminUsers panelUsersAdminUsers1;
    private com.mycompany.proyectofinal.View.PanelUsersCareer panelUsersCareer1;
    public javax.swing.JTabbedPane tbPanel;
    // End of variables declaration//GEN-END:variables
}
