/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectofinal.View;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Marco
 */
public class PanelStudyProgram extends javax.swing.JPanel {

    /**
     * Creates new form PanelUsers
     */
    TableRowSorter<TableModel> sorter;
    public DefaultTableModel model;

    public PanelStudyProgram() {
        initComponents();
    }

    public void setTable(String[] header, String[][] data) {
        List<String[]> filteredData = new ArrayList<>();
        for (String[] row : data) {
            boolean isEmpty = true;
            for (String cell : row) {
                if (cell != null && !cell.trim().isEmpty()) {
                    isEmpty = false;
                    break;
                }
            }
            if (!isEmpty) {
                filteredData.add(row);
            }
        }
        model = new DefaultTableModel(filteredData.toArray(new String[0][]), header);
        this.tblStudyProgram.setModel(model);
        this.tblStudyProgram.setAutoCreateRowSorter(true);
        this.sorter = new TableRowSorter<>(model);
        this.tblStudyProgram.setRowSorter(sorter);
        this.jScrollPane1.setViewportView(this.tblStudyProgram);
    }

    public void listen(ActionListener controller) {
        this.btnAdd.addActionListener(controller);
        this.btnDelete.addActionListener(controller);
        this.btnPatch.addActionListener(controller);
    }

    public void ListenMouse(MouseListener controller) {
        this.tblStudyProgram.addMouseListener(controller);
    }

    public String[] getRow() {
        String[] dataRow = new String[this.tblStudyProgram.getColumnCount()];
        int selectedRow = this.tblStudyProgram.getSelectedRow();
        for (int i = 0; i < dataRow.length; i++) {
            dataRow[i] = this.tblStudyProgram.getValueAt(selectedRow, i).toString();
        }
        return dataRow;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudyProgram = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPatch = new javax.swing.JButton();
        txtFilter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("STUDY PROGRAM");

        tblStudyProgram.setBackground(new java.awt.Color(0, 76, 142));
        tblStudyProgram.setForeground(new java.awt.Color(204, 255, 255));
        tblStudyProgram.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStudyProgram);

        btnAdd.setBackground(new java.awt.Color(150, 186, 224));
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Add");
        btnAdd.setActionCommand("AddStudyProgram");

        btnDelete.setBackground(new java.awt.Color(109, 169, 210));
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.setActionCommand("DeleteStudyProgram");

        btnPatch.setBackground(new java.awt.Color(48, 115, 183));
        btnPatch.setText("Patch");
        btnPatch.setActionCommand("PatchStudyProgram");

        txtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterKeyReleased(evt);
            }
        });

        jLabel3.setText("Filter:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(28, 28, 28)
                        .addComponent(btnDelete)
                        .addGap(26, 26, 26)
                        .addComponent(btnPatch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(232, 232, 232))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd)
                        .addComponent(btnDelete)
                        .addComponent(btnPatch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterKeyReleased
        this.sorter.setRowFilter(RowFilter.regexFilter("(?i)" + txtFilter.getText()));
    }//GEN-LAST:event_txtFilterKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnDelete;
    public javax.swing.JButton btnPatch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblStudyProgram;
    public javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
