/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectofinal.View;

import com.mycompany.proyectofinal.Model.StudyProgramModel;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Marco
 */
public class PanelPlanCourse extends javax.swing.JPanel {

    /**
     * Creates new form PanelUsers
     */
    TableRowSorter<TableModel> sorter;
    public DefaultTableModel model;
    TableRowSorter<TableModel> sorter2;
    public DefaultTableModel model2;

    public PanelPlanCourse() {
        initComponents();
    }

    public void setTableCourse(String[] header, String[][] data) {
        List<String[]> filteredData = new ArrayList<>();
        for (String[] row : data) {
            boolean isEmpty = true;
            for (String cell : row) {
                if (cell != null && !cell.trim().isEmpty()) {
                    isEmpty = false;
                    break;
                }
            }
            if (!isEmpty) {
                filteredData.add(row);
            }
        }
        model = new DefaultTableModel(filteredData.toArray(new String[0][]), header);
        this.tblCourse.setModel(model);
        this.tblCourse.setAutoCreateRowSorter(true);
        this.sorter = new TableRowSorter<>(model);
        this.tblCourse.setRowSorter(sorter);
        this.jScrollPane1.setViewportView(this.tblCourse);
    }

    public void setTableCourseSelect(String[] header, String[][] data) {
        List<String[]> filteredData = new ArrayList<>();
        for (String[] row : data) {
            boolean isEmpty = true;
            for (String cell : row) {
                if (cell != null && !cell.trim().isEmpty()) {
                    isEmpty = false;
                    break;
                }
            }
            if (!isEmpty) {
                filteredData.add(row);
            }
        }
        model2 = new DefaultTableModel(filteredData.toArray(new String[0][]), header);
        this.tblCourseSelect.setModel(model2);
        this.tblCourseSelect.setAutoCreateRowSorter(true);
        this.sorter2 = new TableRowSorter<>(model2);
        this.tblCourseSelect.setRowSorter(sorter2);
        this.jScrollPane2.setViewportView(this.tblCourseSelect);
    }

    public void listen(ActionListener controller) {
        this.btnAsociar.addActionListener(controller);
    }

    public void ListenMouse(MouseListener controller) {
        this.tblCourse.addMouseListener(controller);
        this.tblCourseSelect.addMouseListener(controller);
    }

    public String[] getRowCourse() {
        String[] dataRow = new String[this.tblCourse.getColumnCount()];
        int selectedRow = this.tblCourse.getSelectedRow();
        for (int i = 0; i < dataRow.length; i++) {
            dataRow[i] = this.tblCourse.getValueAt(selectedRow, i).toString();
        }
        return dataRow;
    }

    public String[] getRowCourseSelected() {
        String[] dataRow = new String[this.tblCourseSelect.getColumnCount()];
        int selectedRow = this.tblCourseSelect.getSelectedRow();
        for (int i = 0; i < dataRow.length; i++) {
            dataRow[i] = this.tblCourseSelect.getValueAt(selectedRow, i).toString();
        }
        return dataRow;
    }

    public void inicializarComboBoxStudyProgram(List<StudyProgramModel> elementosList) {
        cbxStudyPlan.removeAllItems();

        for (StudyProgramModel studyProgram : elementosList) {
            if (studyProgram.getCursos().isEmpty()) {
                cbxStudyPlan.addItem(studyProgram.getName());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        btnAsociar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCourseSelect = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxStudyPlan = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        tblCourse.setBackground(new java.awt.Color(48, 115, 183));
        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCourse);

        btnAsociar.setBackground(new java.awt.Color(150, 186, 224));
        btnAsociar.setForeground(new java.awt.Color(0, 0, 0));
        btnAsociar.setText("Asociar");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Filter:");

        txtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PLAN - COURSE");

        tblCourseSelect.setBackground(new java.awt.Color(0, 76, 142));
        tblCourseSelect.setForeground(new java.awt.Color(204, 255, 255));
        tblCourseSelect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCourseSelect);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Lista de cursos para asociar a la carrera");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Lista de cursos ");

        cbxStudyPlan.setBackground(new java.awt.Color(109, 169, 210));
        cbxStudyPlan.setForeground(new java.awt.Color(0, 0, 0));
        cbxStudyPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Plan a asociar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(36, 36, 36)
                            .addComponent(cbxStudyPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAsociar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxStudyPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAsociar)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterKeyReleased
        this.sorter.setRowFilter(RowFilter.regexFilter("(?i)" + txtFilter.getText()));
    }//GEN-LAST:event_txtFilterKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAsociar;
    public javax.swing.JComboBox<String> cbxStudyPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tblCourse;
    public javax.swing.JTable tblCourseSelect;
    public javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
