/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectofinal.View;

import com.mycompany.proyectofinal.Model.CareerModel;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Marco
 */
public class PanelUsersCareer extends javax.swing.JPanel {

    /**
     * Creates new form PanelUsers
     */
    TableRowSorter<TableModel> sorter;
    public DefaultTableModel model;

    public PanelUsersCareer() {
        initComponents();
    }

    public void setTable(String[] header, String[][] data) {
        List<String[]> filteredData = new ArrayList<>();
        for (String[] row : data) {
            boolean isEmpty = true;
            for (String cell : row) {
                if (cell != null && !cell.trim().isEmpty()) {
                    isEmpty = false;
                    break;
                }
            }
            if (!isEmpty) {
                filteredData.add(row);
            }
        }
        model = new DefaultTableModel(filteredData.toArray(new String[0][]), header);
        this.tblUsersCareer.setModel(model);
        this.tblUsersCareer.setAutoCreateRowSorter(true);
        this.sorter = new TableRowSorter<>(model);
        this.tblUsersCareer.setRowSorter(sorter);
        this.jScrollPane1.setViewportView(this.tblUsersCareer);
    }

    public void listen(ActionListener controller) {
        this.btnPatch.addActionListener(controller);
    }

    public void ListenMouse(MouseListener controller) {
        this.tblUsersCareer.addMouseListener(controller);
    }

    public String[] getRow() {
        String[] dataRow = new String[this.tblUsersCareer.getColumnCount()];
        int selectedRow = this.tblUsersCareer.getSelectedRow();
        for (int i = 0; i < dataRow.length; i++) {
            dataRow[i] = this.tblUsersCareer.getValueAt(selectedRow, i).toString();
        }
        return dataRow;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsersCareer = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnPatch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();

        jLabel1.setText("PanelUsers");

        jLabel2.setText("Bienvenido: ");

        lbUser.setText(" ");

        jLabel3.setText("Registrado como:  Usuario con privilegios");

        tblUsersCareer.setBackground(new java.awt.Color(0, 76, 142));
        tblUsersCareer.setForeground(new java.awt.Color(204, 255, 255));
        tblUsersCareer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsersCareer);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Modificar la Carrera de los usuarios");

        btnPatch.setBackground(new java.awt.Color(48, 115, 183));
        btnPatch.setText("Patch");
        btnPatch.setActionCommand("PatchUser");

        jLabel5.setText("Filter:");

        txtFilter.setBackground(new java.awt.Color(109, 169, 210));
        txtFilter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(btnPatch)))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPatch))
                .addContainerGap(162, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterKeyReleased
        this.sorter.setRowFilter(RowFilter.regexFilter("(?i)" + txtFilter.getText()));
    }//GEN-LAST:event_txtFilterKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnPatch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbUser;
    public javax.swing.JTable tblUsersCareer;
    public javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
